from __future__ import annotations

from typing import List, Optional, Tuple


def build_compression_prompt(question: str, predict: str) -> str:
    """
    构造用于精简答案的 Prompt 模板。

    输入:
        question: 问题
        predict: 模型原始预测答案，可能包含冗余信息
    输出:
        一个完整的 Prompt 字符串
    """
    prompt = f"""
You are an answer compressor.
I will give you a question and a model prediction (predict).
The predict may contain extra explanations or irrelevant details.

Your task:
- Keep only the essential information from the predict that directly answers the question.
- Output must be concise (a short phrase or word).
- Do NOT repeat the question, do NOT explain, do NOT include extra text.
- Format: only the final answer.

Examples:
Q: Which magazine was started first Arthur's Magazine or First for Women?
Predict: Arthur's Magazine was started in the 19th century and First for Women is much later.
Final Answer: Arthur's Magazine

Q: What nationality was James Henry Miller's wife?
Predict: James Henry Miller's wife was American, she was born in the United States.
Final Answer: American

Q: What U.S Highway gives access to Zilpo Road, and is also known as Midland Trail?
Predict: Zilpo Road is accessed via U.S. Route 60, also called the Midland Trail.
Final Answer: US 60

Now, based on the given question and predict, output only the final answer.

Q: {question}
Predict: {predict}
Final Answer:
"""
    return prompt


def build_subquestion_prompt(
    main_query: str,
    history: Optional[List[Tuple[str, str]]] = None,
) -> str:
    """构建严格控制、统一风格的子问题生成提示词。"""
    if history and len(history) > 0:
        past = ""
        for i, (subq, ans) in enumerate(history):
            past += f"Intermediate query {i + 1}: {subq}\nIntermediate answer {i + 1}: {ans}\n"
        past = past.strip()
    else:
        past = "Nothing yet"

    prompt = f"""You are an intelligent research assistant that answers complex questions by iteratively generating simple, focused sub-questions for web or document retrieval.

Your goal is to decompose the main question into a sequence of small, concrete questions. Each sub-question should help uncover key information needed to ultimately answer the main question.

## Previous intermediate queries and answers
{past}


## Main query to answer
{main_query}

Rules:
1. Use history to avoid asking already-answered questions.
2. Ask exactly one concise follow-up question when key facts are still missing.
3. Do not output explanations or extra text.
"""
    return prompt


def build_nq_prompt(
    question: str,
    reference: str,
) -> str:
    """构建 NQ 数据集上的抽取式问答提示词。"""

    prompt = f"""Answer the question based on the given document. Only give me the answer and do not output any other words.

The following are given documents.

{reference}

Question: {question}
Answer:"""

    return prompt


def build_answer_prompt(sub_query: str, docs: List[str]) -> str:
    """构造子问题回答提示词，要求仅基于给定文档回答。"""
    context = ""
    for doc in docs:
        context += f"{doc}\n\n"

    return f"""Given the following documents, generate an appropriate answer for the query. DO NOT hallucinate any information, only use the provided documents to generate the answer. Respond "No relevant information found" if the documents do not contain useful information.

Given the following documents:
{context.strip()}

Answer the question:
{sub_query}

Respond with a concise answer only, do not explain yourself or output anything else.
"""


def build_final_answer_prompt(
    query: str,
    qa_history: List[Tuple[str, str]],
    documents: List[str],
    task_desc: str = "Combine all useful information to produce a concise and accurate final answer.",
) -> str:
    """构建最终答案生成的提示词。"""
    past = ""
    for idx, (subq, suba) in enumerate(qa_history):
        past += f"""Intermediate query {idx + 1}: {subq}
Intermediate answer {idx + 1}: {suba}\n"""
    past = past.strip() or "Nothing yet"

    context = ""
    if documents:
        for idx, doc in enumerate(documents):
            context += f"""Doc {idx}: {doc}\n\n"""
    context = context.strip() or "No external documents provided."

    prompt = f"""You are a reasoning assistant tasked with producing a final, factual answer to a complex question.

The following intermediate questions, answers, and retrieved documents are provided as context. Intermediate answers were generated by an LLM and may contain noise or inaccuracies — you should carefully cross-check and synthesize information.

## Documents
{context}

## Intermediate queries and answers
{past}

## Task description
{task_desc}

## Main query
{query}

Respond with only the final answer, without any explanations or reasoning.
"""
    return prompt


def build_iteration_control_prompt(
    main_query: str,
    history: Optional[List[Tuple[str, str]]] = None,
    evidence_summary: str = "No retrieved evidence yet.",
    iteration: int = 1,
    max_iterations: int = 4,
) -> str:
    """
    迭代控制模板：输出本轮 CONTINUE 的理由。

    说明：该模板风格与本模块其余模板保持一致，输出严格 JSON 便于程序解析。
    """
    if history and len(history) > 0:
        past = ""
        for i, (subq, ans) in enumerate(history):
            past += f"Intermediate query {i + 1}: {subq}\nIntermediate answer {i + 1}: {ans}\n"
        past = past.strip()
    else:
        past = "Nothing yet"

    prompt = f"""You are an iteration controller for a retrieval-augmented QA pipeline.

Your task is to decide whether we should continue asking more intermediate questions or stop and produce the final answer.

## Main query
{main_query}

## Current iteration
{iteration}

## Max iterations
{max_iterations}

## Previous intermediate queries and answers
{past}

## Retrieved evidence summary
{evidence_summary}

Rules:
1. Judge with both history and retrieved evidence summary (do not rely on history alone).
2. Output CONTINUE with a concise reason for the current iteration status.
4. Output STRICT JSON only (no markdown, no extra text):
{{"action":"CONTINUE","reason":"..."}}
"""
    return prompt
